### ISSUE TITLE
navigation in indigo

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_morse#92]
The navigation in the simulation environment doesn't work properly in indigo. The robot generates the plan and rotates towards the goal normally, but then in it doesn't move forward. `/cmd_vel` looks like this:

```
linear: 
  x: 0.100002683699
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0
```

If i drive him in blender towards the goal it will then rotate into position and achieve the goal, so it's some weird thing with the linear velocities
