### ISSUE TITLE
Laser message has no intensities, only ranges

### ISSUE THREAD

**Issue by nilsbore** [strands-project/strands_morse#98]
This is different from how the actual laser behaves. We should probably have a constant intensity in the laser messages in simulation. See example of simulation laser message below:

```
header: 
  seq: 12
  stamp: 
    secs: 1425722175
    nsecs: 704088211
  frame_id: /base_laser_link
angle_min: -1.57079637051
angle_max: 1.57079637051
angle_increment: 0.0174532923847
time_increment: 0.000138888892252
scan_time: 1.0
range_min: 0.300000011921
range_max: 30.0
ranges: [0.7400559782981873, ... , 5.430670261383057]
intensities: []
```

The intensities vector should be as long as the ranges.
